{
 "title": "server_cluster_2",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Server2 - All Volumes",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserver2_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserver2_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nserver2_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nserver2_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol1_total, server2_vol2_total,server2_vol1_used, server2_vol2_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_size - r.total_used) }))\r\n|> drop(columns: [\"_time\"])\r\n|> rename(columns: {total_size: \"Total\"})\r\n|> rename(columns: {_value: \"Free\"})\r\n|> rename(columns: {total_used: \"Used\"})\r\n|> yield()\r\n"
    }
   ]
  },
  {
   "title": "Server_NVR - All Volumes",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nservernvr_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nservernvr_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nservernvr_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] ==\"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nservernvr_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [servernvr_vol1_total, servernvr_vol2_total, servernvr_vol1_used, servernvr_vol2_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_size - r.total_used) }))\r\n|> drop(columns: [\"_time\"])\r\n|> rename(columns: {total_size: \"Total\"})\r\n|> rename(columns: {_value: \"Free\"})\r\n|> rename(columns: {total_used: \"Used\"})\r\n|> yield()\r\n"
    }
   ]
  },
  {
   "title": "Server-Plex - All Volumes",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserverplex_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\n\r\nserverplex_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [serverplex_vol1_total,serverplex_vol1_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_size - r.total_used) }))\r\n|> drop(columns: [\"_time\"])\r\n|> rename(columns: {total_size: \"Total\"})\r\n|> rename(columns: {_value: \"Free\"})\r\n|> rename(columns: {total_used: \"Used\"})\r\n|> yield()\r\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserver2_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserver2_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nserver2_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nserver2_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol1_total, server2_vol2_total,server2_vol1_used, server2_vol2_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_used / r.total_size)*100.0 }))\r\n|> drop(columns: [\"total_size\", \"total_used\", \"_time\"])\r\n|> rename(columns: {_value: \"% Space Used\"})\r\n|> yield()"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nservernvr_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nservernvr_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nservernvr_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] ==\"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nservernvr_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [servernvr_vol1_total, servernvr_vol2_total, servernvr_vol1_used, servernvr_vol2_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_used / r.total_size)*100.0 }))\r\n|> drop(columns: [\"total_size\", \"total_used\", \"_time\"])\r\n|> rename(columns: {_value: \"% Space Used\"})\r\n|> yield()"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserverplex_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nserverplex_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [serverplex_vol1_total, serverplex_vol1_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_used / r.total_size)*100.0 }))\r\n|> drop(columns: [\"total_size\", \"total_used\", \"_time\"])\r\n|> rename(columns: {_value: \"% Space Used\"})\r\n|> yield()"
    }
   ]
  },
  {
   "title": "All Servers - All Volumes",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserver2_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserver2_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nservernvr_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nservernvr_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserverplex_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nserver2_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nserver2_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nservernvr_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] ==\"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nservernvr_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nserverplex_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol1_total, server2_vol2_total, servernvr_vol1_total, servernvr_vol2_total, serverplex_vol1_total,server2_vol1_used, server2_vol2_used, servernvr_vol1_used, servernvr_vol2_used, serverplex_vol1_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_size - r.total_used) }))\r\n|> rename(columns: {_value: \"Free\"})\r\n|> rename(columns: {total_size: \"Total\"})\r\n|> rename(columns: {total_used: \"Used\"})\r\n|> drop(columns: [\"_time\"])\r\n|> yield()\r\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserver2_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n    |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserver2_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n    |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nservernvr_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n    |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nservernvr_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n    |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserverplex_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n    |> limit(n: 1)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nserver2_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n    |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nserver2_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n    |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nservernvr_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] ==\"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n    |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nservernvr_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n    |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\nserverplex_vol1_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n    |> limit(n: 1)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol1_total, server2_vol2_total, servernvr_vol1_total, servernvr_vol2_total, serverplex_vol1_total,server2_vol1_used, server2_vol2_used, servernvr_vol1_used, servernvr_vol2_used, serverplex_vol1_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_used / r.total_size)*100.0 }))\r\n|> drop(columns: [\"total_size\", \"total_used\"])\r\n|> rename(columns: {_value: \"% Space Used\"})\r\n|> yield()"
    }
   ]
  },
  { "title": "Server2", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Server 2 - Disk Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sort" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -1m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_status\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk1\" or r[\"disk_name\"] == \"Disk1(DX517-1)\" or r[\"disk_name\"] == \"Disk2\" or r[\"disk_name\"] == \"Disk2(DX517-1)\" or r[\"disk_name\"] == \"Disk3\" or r[\"disk_name\"] == \"Disk3(DX517-1)\" or r[\"disk_name\"] == \"Disk4\" or r[\"disk_name\"] == \"Disk4(DX517-1)\" or r[\"disk_name\"] == \"Disk5(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_start\", \"_time\", \"_stop\", \"_field\", \"_measurement\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"}) \r\n  |> rename(columns: {disk_name: \"Disk\"}) "
    }
   ]
  },
  {
   "title": "Server 2 - RAID Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sort" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -1m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_status\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume1\" or r[\"raid_name\"] == \"Volume2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_start\", \"_time\", \"_stop\", \"_field\", \"_measurement\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"}) \r\n  |> rename(columns: {raid_name: \"Volume Name\"}) "
    }
   ]
  },
  {
   "title": "Server2 - Volume 1",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "server2_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_total_size\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserver2_vol1_free=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_free_size\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"vol_free\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol1_total, server2_vol1_free])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_free\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          vol_free: r.vol_free + accumulator.vol_free\r\n         }),\r\n        identity: {total_size: 0.0, vol_free: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_size - r.vol_free) }))\r\n|> drop(columns: [\"_time\"])\r\n|> rename(columns: {_value: \"Used\"})\r\n|> rename(columns: {total_size: \"Total\"})\r\n|> rename(columns: {vol_free: \"Free\"})\r\n|> yield()\r\n"
    }
   ]
  },
  {
   "title": "Server2 - Volume 2",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "server2_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_total_size\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserver2_vol1_free=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_free_size\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"vol_free\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol1_total, server2_vol1_free])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_free\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          vol_free: r.vol_free + accumulator.vol_free\r\n         }),\r\n        identity: {total_size: 0.0, vol_free: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_size - r.vol_free) }))\r\n|> drop(columns: [\"_time\"])\r\n|> rename(columns: {_value: \"Used\"})\r\n|> rename(columns: {total_size: \"Total\"})\r\n|> rename(columns: {vol_free: \"Free\"})\r\n|> yield()\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 } },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserver2_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nserver2_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol2_total, server2_vol2_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_used / r.total_size)*100.0 }))\r\n|> drop(columns: [\"total_size\", \"total_used\", \"_time\"])\r\n|> rename(columns: {_value: \"% Space Used\"})\r\n|> yield()\r\n\r\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserver2_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nserver2_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol2_total, server2_vol2_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_used / r.total_size)*100.0 }))\r\n|> drop(columns: [\"total_size\", \"total_used\", \"_time\"])\r\n|> rename(columns: {_value: \"% Space Used\"})\r\n|> yield()\r\n\r\n"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system_status\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"})"
    }
   ]
  },
  {
   "title": "System Fan Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fan_status\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"})"
    }
   ]
  },
  {
   "title": "System Uptine",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> map(fn: (r) => ({ r with _value: r._value / 100.0 }))\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Uptime\"})"
    }
   ]
  },
  {
   "title": "DSM Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dsm_version\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n // |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n // |> rename(columns: {_value: \"Status\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upgrade_status\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \" \"})"
    }
   ]
  },
  { "title": "Server_NVR", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Server_NVR - Disk Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "sort" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -1m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_status\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk1\" or r[\"disk_name\"] == \"Disk1(DX517-1)\" or r[\"disk_name\"] == \"Disk2\" or r[\"disk_name\"] == \"Disk2(DX517-1)\" or r[\"disk_name\"] == \"Disk3\" or r[\"disk_name\"] == \"Disk3(DX517-1)\" or r[\"disk_name\"] == \"Disk4\" or r[\"disk_name\"] == \"Disk4(DX517-1)\" or r[\"disk_name\"] == \"Disk5(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_start\", \"_time\", \"_stop\", \"_field\", \"_measurement\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"}) \r\n  |> rename(columns: {disk_name: \"Disk\"}) "
    }
   ]
  },
  {
   "title": "Server_NVR - RAID Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "sort" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -1m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_status\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume1\" or r[\"raid_name\"] == \"Volume2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_start\", \"_time\", \"_stop\", \"_field\", \"_measurement\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"}) \r\n  |> rename(columns: {raid_name: \"Volume Name\"}) "
    }
   ]
  },
  {
   "title": "Server_NVR - Volume 1",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "server2_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_total_size\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserver2_vol1_free=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_free_size\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"vol_free\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol1_total, server2_vol1_free])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_free\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          vol_free: r.vol_free + accumulator.vol_free\r\n         }),\r\n        identity: {total_size: 0.0, vol_free: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_size - r.vol_free) }))\r\n|> drop(columns: [\"_time\"])\r\n|> rename(columns: {_value: \"Used\"})\r\n|> rename(columns: {total_size: \"Total\"})\r\n|> rename(columns: {vol_free: \"Free\"})\r\n|> yield()\r\n"
    }
   ]
  },
  {
   "title": "Server_NVR - Volume 2",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "server2_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_total_size\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserver2_vol1_free=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_free_size\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume2\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"vol_free\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol1_total, server2_vol1_free])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_free\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          vol_free: r.vol_free + accumulator.vol_free\r\n         }),\r\n        identity: {total_size: 0.0, vol_free: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_size - r.vol_free) }))\r\n|> drop(columns: [\"_time\"])\r\n|> rename(columns: {_value: \"Used\"})\r\n|> rename(columns: {total_size: \"Total\"})\r\n|> rename(columns: {vol_free: \"Free\"})\r\n|> yield()\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 } },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserver2_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nserver2_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol2_total, server2_vol2_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_used / r.total_size)*100.0 }))\r\n|> drop(columns: [\"total_size\", \"total_used\", \"_time\"])\r\n|> rename(columns: {_value: \"% Space Used\"})\r\n|> yield()\r\n\r\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserver2_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nserver2_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume2\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol2_total, server2_vol2_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_used / r.total_size)*100.0 }))\r\n|> drop(columns: [\"total_size\", \"total_used\", \"_time\"])\r\n|> rename(columns: {_value: \"% Space Used\"})\r\n|> yield()\r\n\r\n"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system_status\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"})"
    }
   ]
  },
  {
   "title": "System Fan Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fan_status\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"})"
    }
   ]
  },
  {
   "title": "System Uptine",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> map(fn: (r) => ({ r with _value: r._value / 100.0 }))\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Uptime\"})"
    }
   ]
  },
  {
   "title": "DSM Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dsm_version\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upgrade_status\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \" \"})"
    }
   ]
  },
  { "title": "Server-PLEX", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Server-PLEX - Disk Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "sort" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -1m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_status\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk1\" or r[\"disk_name\"] == \"Disk2\" or r[\"disk_name\"] == \"Disk3\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_start\", \"_time\", \"_stop\", \"_field\", \"_measurement\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"}) \r\n  |> rename(columns: {disk_name: \"Disk\"}) "
    }
   ]
  },
  {
   "title": "Server-PLEX - Volume 1",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "server2_vol1_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_total_size\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\nserver2_vol1_free=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_free_size\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume1\")\r\n  |> aggregateWindow(every: 1h, fn: last)\r\n  |> rename(columns: {_value: \"vol_free\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol1_total, server2_vol1_free])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_free\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          vol_free: r.vol_free + accumulator.vol_free\r\n         }),\r\n        identity: {total_size: 0.0, vol_free: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_size - r.vol_free) }))\r\n|> drop(columns: [\"_time\"])\r\n|> rename(columns: {_value: \"Used\"})\r\n|> rename(columns: {total_size: \"Total\"})\r\n|> rename(columns: {vol_free: \"Free\"})\r\n|> yield()\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 8, "w": 11, "x": 8, "y": 37 } },
  {
   "title": "Server-PLEX - RAID Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "sort" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -1m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_raid\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raid_status\")\r\n  |> filter(fn: (r) => r[\"raid_name\"] == \"Volume1\" or r[\"raid_name\"] == \"Volume2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_start\", \"_time\", \"_stop\", \"_field\", \"_measurement\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"}) \r\n  |> rename(columns: {raid_name: \"Volume Name\"}) "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//TOTAL AVAILABLE SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\nserver2_vol2_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_totalsize\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"total_size\"})\r\n\r\n////////////////////////////////////////////////\r\n//USED SPACE ON THE DIFFERENT VOLUMES\r\n////////////////////////////////////////////////\r\n\r\nserver2_vol2_used=from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vol_used\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume\"] == \"/volume1\")\r\n  |> aggregateWindow(every: 1h, fn: first)\r\n  |> rename(columns: {_value: \"vol_used\"})\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [server2_vol2_total, server2_vol2_used])\r\n|> group(columns: [\"_time\"], mode:\"by\")\r\n|> fill(column: \"total_size\", value: 0.0)\r\n|> fill(column: \"vol_used\", value: 0.0)\r\n|> reduce(\r\n       fn: (r, accumulator) => ({\r\n          total_size: r.total_size + accumulator.total_size,\r\n          total_used: r.vol_used + accumulator.total_used\r\n         }),\r\n        identity: {total_size: 0.0, total_used: 0.0},\r\n    )\r\n|> map(fn: (r) => ({ r with _value: (r.total_used / r.total_size)*100.0 }))\r\n|> drop(columns: [\"total_size\", \"total_used\", \"_time\"])\r\n|> rename(columns: {_value: \"% Space Used\"})\r\n|> yield()\r\n\r\n"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system_status\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"})"
    }
   ]
  },
  {
   "title": "System Fan Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fan_status\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"})"
    }
   ]
  },
  {
   "title": "System Uptine",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> map(fn: (r) => ({ r with _value: r._value / 100.0 }))\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Uptime\"})"
    }
   ]
  },
  {
   "title": "DSM Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dsm_version\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \"Status\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upgrade_status\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> last()\r\n  |> limit(n: 1)\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"_time\", \"nas_name\"])\r\n  |> rename(columns: {_value: \" \"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "////////////////////////////////////////////////\r\n//Memory Used Calculation\r\n////////////////////////////////////////////////\r\nmem_avail_real=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_avail_real\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_avail_real\"})\r\n\r\nmem_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_total\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_total\"})\r\n\r\nmem_buffer=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_buffer\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_buffer\"})\r\n\r\nmem_cached=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_cached\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_cached\"})\r\n\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [mem_avail_real, mem_total, mem_cached, mem_buffer])\r\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ r with _value: ((r.mem_total-r.mem_avail_real-r.mem_buffer-r.mem_cached)/r.mem_total) * 100.0 }))\r\n|> drop(columns: [\"mem_avail_real\", \"mem_buffer\", \"mem_cached\", \"mem_total\", \"_start\", \"_stop\", \"nas_name\", \"_measurement\"])\r\n|> rename(columns: {_value: \"Server 2\"})\r\n|> yield()\r\n"
    },
    {
     "query": "////////////////////////////////////////////////\r\n//Memory Used Calculation\r\n////////////////////////////////////////////////\r\nmem_avail_real=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_avail_real\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_avail_real\"})\r\n\r\nmem_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_total\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_total\"})\r\n\r\nmem_buffer=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_buffer\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_buffer\"})\r\n\r\nmem_cached=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_cached\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_cached\"})\r\n\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [mem_avail_real, mem_total, mem_cached, mem_buffer])\r\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ r with _value: ((r.mem_total-r.mem_avail_real-r.mem_buffer-r.mem_cached)/r.mem_total) * 100.0 }))\r\n|> drop(columns: [\"mem_avail_real\", \"mem_buffer\", \"mem_cached\", \"mem_total\", \"_start\", \"_stop\", \"nas_name\", \"_measurement\"])\r\n|> rename(columns: {_value: \"Server_PLEX\"})\r\n|> yield()\r\n"
    },
    {
     "query": "////////////////////////////////////////////////\r\n//Memory Used Calculation\r\n////////////////////////////////////////////////\r\nmem_avail_real=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_avail_real\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_avail_real\"})\r\n\r\nmem_total=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_total\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_total\"})\r\n\r\nmem_buffer=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_buffer\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_buffer\"})\r\n\r\nmem_cached=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_cached\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  //|> rename(columns: {_value: \"mem_cached\"})\r\n\r\n\r\n////////////////////////////////////////////////\r\n//COMBINE ALL TABLES INTO ONE TABLE\r\n////////////////////////////////////////////////\r\n\r\noverview = union(tables: [mem_avail_real, mem_total, mem_cached, mem_buffer])\r\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ r with _value: ((r.mem_total-r.mem_avail_real-r.mem_buffer-r.mem_cached)/r.mem_total) * 100.0 }))\r\n|> drop(columns: [\"mem_avail_real\", \"mem_buffer\", \"mem_cached\", \"mem_total\", \"_start\", \"_stop\", \"nas_name\", \"_measurement\"])\r\n|> rename(columns: {_value: \"Server_NVR\"})\r\n|> yield()\r\n"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_gpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpuMemoryUsed\" or r[\"_field\"] == \"gpuMemoryTotal\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n   |> map(fn: (r) => ({r with _value: (r.gpuMemoryUsed / r.gpuMemoryTotal) * 100.0}))\r\n     |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"gpuMemoryTotal\", \"gpuMemoryUsed\"])\r\n|> rename(columns: {_value: \"Server_NVR GPU\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "CPU/GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\"])\r\n|> rename(columns: {_value: \"Server-PLEX\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\"])\r\n|> rename(columns: {_value: \"Server2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\"])\r\n|> rename(columns: {_value: \"Server_NVR_CPU\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_gpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_utilization\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\"])\r\n|> rename(columns: {_value: \"Server_NVR_GPU\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server 2 System Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system_temp\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\"])\r\n|> rename(columns: {_value: \"CPU\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk3\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk3\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk4\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk4\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk1(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk1(DX517-1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk2(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk2(DX517-1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk3(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk3(DX517-1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk4(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk4(DX517-1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk5(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk5(DX517-1)\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server_NVR System Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system_temp\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\"])\r\n|> rename(columns: {_value: \"CPU\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk3\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk3\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk4\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk4\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk1(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk1(DX517-1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk2(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk2(DX517-1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk3(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk3(DX517-1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk4(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk4(DX517-1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk5(DX517-1)\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk5(DX517-1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_gpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpuTemperature\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\"])\r\n|> rename(columns: {_value: \"GPU\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server-PLEX System Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system_temp\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\"])\r\n|> rename(columns: {_value: \"CPU\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_temp\")\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"Disk3\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value*(9.0/5.0))+32.0 }))\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_name\"])\r\n|> rename(columns: {_value: \"Disk3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server Room Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"house/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"House_Temp_Hum\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"average\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"Server\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n   |> drop(columns: [\"_start\", \"_stop\", \"sensor_name\", \"_measurement\", \"_field\"])\r\n    |> rename(columns: {_value: \"Average\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"house/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"House_Temp_Hum\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"Server\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n     |> drop(columns: [\"_start\", \"_stop\", \"sensor_name\", \"_measurement\", \"_field\"])\r\n   |> rename(columns: {_value: \"sensor1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"house/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"House_Temp_Hum\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor2\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"Server\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n     |> drop(columns: [\"_start\", \"_stop\", \"sensor_name\", \"_measurement\", \"_field\"])\r\n  |> rename(columns: {_value: \"sensor2\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server2 Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 3\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 4\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 3\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 4\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata9\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 5\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server_NVR Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sda\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sdb\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 3\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sdd\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 4\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sdea\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sdeb\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sdec\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 3\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sded\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 4\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sdee\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 5\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server-PLEX Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 3\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol1 Disk 4\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 3\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 4\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_disk\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata9\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"disk_path\"])\r\n|> rename(columns: {_value: \"Vol2 Disk 5\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server2  ||  Server_NVR  ||  Server-Plex  ----    Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n|> rename(columns: {_value: \"Server2 - Volume1 Load\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n|> rename(columns: {_value: \"Server2 - Volume2 Load\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n|> rename(columns: {_value: \"Server-PLEX - Volume1 Load\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n|> rename(columns: {_value: \"Server_NVR - Volume1 Load\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_load\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n|> rename(columns: {_value: \"Server_NVR - Volume2 Load\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server2 Volume Activity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_reads\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"Volume1 READ\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_reads\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"Volume2 READ\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_writes\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"Volume1 WRITE\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_writes\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"Volume2 WRITE\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server_NVR Volume Activity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_reads\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"Volume1 READ\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_reads\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"Volume2 READ\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_writes\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"Volume1 WRITE\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_writes\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"Volume2 WRITE\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server-PLEX Volume Activity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_reads\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"Volume1 READ\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_volume\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_writes\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"volume_path\"] == \"md3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"volume_path\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"Volume1 WRITE\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server 2 - Network Activity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth0\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN1 Received (VLAN 101)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN2 Received (VLAN 1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth0\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN1 Sent (VLAN 101)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server2\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN2 Sent (VLAN 1)\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server_NVR - Network Activity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth0\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN1 Received (VLAN 100)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN2 Received (VLAN 101)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth0\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN1 Sent (VLAN 100)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN2 Sent (VLAN 101)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth3\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN4 Received (VLAN 1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth3\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN4 Sent (VLAN 1)\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server-PLEX - Network Activity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth0\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN1 Received (VLAN 101)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN2 Received (VLAN 1)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth0\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN1 Sent (VLAN 101)\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"eth1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n      |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\", \"interface_name\"])\r\n  |> derivative(\r\n    unit: 1s,\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    timeColumn: \"_time\",\r\n)\r\n|> rename(columns: {_value: \"LAN2 Sent (VLAN 1)\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Server NVR - GPU Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_gpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpuFanSpeed\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server_NVR\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"nas_name\", \"_measurement\", \"_field\"])\r\n|> rename(columns: {_value: \"GPU Fan Speed Command\"})\r\n  |> yield()"
    }
   ]
  }
 ]
}